server:
  port: 8085
spring:
  application:
    name: user-identity-service
  
  # MongoDB Configuration
  data:
    mongodb:
      # Format: ${VARIABLE_NAME:FALLBACK_VALUE}
      uri: ${MONGODB_URI:mongodb+srv://nithika151_db_user:nithika123@cluster0.kd7jqcp.mongodb.net/user_db?retryWrites=true&w=majority}

# OpenAPI & Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  writer-with-default-pretty-printer: true

# Inter-Service Communication Endpoints
services:
  catalog-node: ${CATALOG_SERVICE_URL:https://menu-service-production-048a.up.railway.app}
  order-node: ${ORDER_SERVICE_URL:https://order-service-production-5615.up.railway.app}
  notification-node: ${NOTIFICATION_SERVICE_URL:https://notification-service-production-e192.up.railway.app/}