spring:
  application:
    name: user-identity-service

# OpenAPI & Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  writer-with-default-pretty-printer: true