spring:
  application:
    name: user-identity-service

# OpenAPI & Swagger UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  writer-with-default-pretty-printer: true

# Inter-Service Communication Endpoints
services:
  # Uses Environment Variables from Render, with a fallback for local testing
  catalog-node: ${CATALOG_SERVICE_URL:https://gourmet-catalog.onrender.com}
  order-node: ${ORDER_SERVICE_URL:https://gourmet-order.onrender.com}